language: node_js
node_js:
  - lts/*
notifications:
  email:
    on_success: change
    on_failure: always
before_script:
  - npm run build
script:
  - npm test
  - codecov
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run _version
    on:
      branch: master
      repo: smockle/homebridge-lutron-caseta
      tags: false
  - provider: npm
    skip_cleanup: true
    email: bot@smockle.com
    api_key:
      secure: uH895XcBd9p5+E0wNk1tpc8C8VUUWOJlqlmfIt2+SYn4TCzn8rUwDdArNa+XqSsudzV2tUbmHsHQU4urFCaNifF+3SO7i+EKUg/SkPr6aVh+gnQN4WMFme2UA4RR3Kru113wMdFO2Z8Opn5MQfsEKFNbaCd4xcLaPsaAEcgPPhHc3em4ZeqD1W0fPHHkwFzX6NZXl84zCowIU0fHpeQIldqpVG1shsoAq3DHJurtT04lipohZVGZDW0yEfGR0gzoarkMQBVQK2nxNkrNvPs8oyPuUiSiC+xFZ1gS5Vbg1VlyLilv1eIidIc9oG5sLzIAViDcJiGNZvGaSS3dLRe+7qHLbUZI9gnfefN2GBu73F+e3vkDV073NXqZPvHB9BuqeNwsuxaqVTnYDzvlYJcl/+O4mpnTIjIRsk88g/C3J+pY0alajyM7a+IZQycUj0ykcc/X6N19ZyMizEHwJQZEvJgZn1pBUS3MXPDSdmwSZ8CKG6uPhcRhoM2QwamcL4Zft73s7nlzjFRuT5VjGXrlLiEeDFwhmHQIGIWti3JBYyBZo8VndLnMx96yVXUmxorRxvc8+Fex8PsFwsT0rtJ5ZkUyoiJWFL1ReXan7W9esQJonohPEyWhFnZRG5mKtZQxiDAlFEhGch+V5HXg2FfOy3IQAjSkaMHg/PZXU2KWH8s=
    on:
      branch: master
      repo: smockle/homebridge-lutron-caseta
      tags: false
